### ISSUE TITLE
NPM/GITHUB access

### ISSUE THREAD

**Issue by alexander-akait** [css-modules/postcss-icss-keyframes#2]
/cc @TrySound 

Hi!

Looks i need access to `postcss-icss-values`, `postcss-icss-selectors`, `postcss-icss-composes` and `postcss-icss` too, thanks!

**Comment by TrySound** [comment]
@evilebottnawi You have an access to all these repos as a part of postcss team but I just added you everywhere as a collaborator too. In npm I added you before too. Make sure you accepted invitations.

**Comment by alexander-akait** [comment]
@TrySound thanks all good :+1:
